// // generated by mBlock5 for <your product>
// // codes make you happy

// #include <Arduino.h>
// #include <Wire.h>
// #include <SoftwareSerial.h>

// float number = 0;

// const int segmentPins[7] = { 8, 7, 6, 5, 4, 3, 2};//chan 2 noi voi a, chan 8 noi voi g
// const byte digits[10][8] = {
// //.  g  f  e  d  c  b  a
// { 1, 1, 0, 0, 0, 0, 0, 0}, // 0
// { 1, 1, 1, 1, 1, 0, 0, 1}, // 1
// { 1, 0, 1, 0, 0, 1, 0, 0}, // 2
// { 1, 0, 1, 1, 0, 0, 0, 0}, // 3
// { 1, 0, 0, 1, 1, 0, 0, 1}, // 4
// { 1, 0, 0, 1, 0, 0, 1, 0}, // 5
// { 1, 0, 0, 0, 0, 0, 1, 0}, // 6
// { 1, 1, 1, 1, 1, 0, 0, 0}, // 7
// { 1, 0, 0, 0, 0, 0, 0, 0}, // 8
// { 1, 0, 0, 1, 0, 0, 0, 0} // 9
// };

// void _delay(float seconds) {
//   long endTime = millis() + seconds * 1000;
//   while(millis() < endTime) _loop();
// }

// void setup() {
//   pinMode(A0+0,INPUT);
//   for(int i=0;i<7;i++)
//       pinMode(segmentPins[i],OUTPUT);
//   while(1) {
//       number = map(analogRead(A0+0), 0, 1023, 0, 9);
//        for ( int i = 0; i < 7; i++)
//         {
//           if( 1)
//           digitalWrite(segmentPins[i], digits[(int)number][i+1]);
//           else
//           digitalWrite(segmentPins[i], not(digits[(int)number][i+1]));
//         }

//       _loop();
//   }

// }

// void _loop() {
// }

// // void loop() {
//   _loop();
// }

// /*How to use a seven-segment LED display.
//   created by the SriTu Tech team.
//   Read the code below and use it for any of your creations.
//   https://srituhobby.com
// */
// byte pin[] = {2, 3, 4, 5, 6, 7, 8, 9};//arduino pin array
 
// int number[9][8] = {//number array
//   {1, 1, 0, 0, 0, 1, 1, 1},//1
//   {0, 0, 1, 0, 0, 0, 1, 0},//2
//   {1, 0, 0, 0, 0, 0, 1, 0},//3
//   {1, 1, 0, 0, 0, 1, 0, 0},//4
//   {1, 0, 0, 0, 1, 0, 0, 0},//5
//   {0, 0, 0, 0, 1, 0, 0, 0},//6
//   {1, 1, 0, 0, 0, 0, 0, 1},//7
//   {0, 0, 0, 0, 0, 0, 0, 0},//8
//   {1, 1, 0, 0, 0, 0, 0, 0},//9
// };
 
// void setup() {
//   for (byte a = 0; a < 8; a++) {
//     pinMode(pin[a], OUTPUT);//define output pins
//   }
// }
 
// void loop() {
//   for (int a = 0; a < 9; a++) {
//     for (int b = 0; b < 8; b++) {
//       digitalWrite(pin[b], number[a][b]);//display numbers
//     }
//     delay(500);//delay
//   }
// }