name: Update README with Wiring Diagram

on:
  push:
    branches:
      - test_workflow

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Find Subdirectory
        id: find-subdirectory
        run: |
          # Retrieve the subdirectory name where the latest commit was made
          SUBDIRECTORY=$(dirname $(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep "/Projects/[^/]*$"))

          echo "Subdirectory: $SUBDIRECTORY"
          echo "::set-output name=subdirectory::$SUBDIRECTORY"

      - name: Find Wiring Diagram file
        id: wiring-diagram
        run: |
          SUBDIRECTORY=${{ steps.find-subdirectory.outputs.subdirectory }}
          DIAGRAM_PATH=$(find "Projects/$SUBDIRECTORY" -type f -name '* Wiring Diagram.png' -print -quit)

          if [[ -n "$DIAGRAM_PATH" ]]; then
            echo "Wiring Diagram Path: $DIAGRAM_PATH"
            echo "::set-output name=path::$DIAGRAM_PATH"
          else
            echo "No Wiring Diagram file found in the $SUBDIRECTORY subdirectory."
            exit 1
          fi

      - name: Update README
        run: |
          DIAGRAM_PATH="${{ steps.wiring-diagram.outputs.path }}"
          SUBDIRECTORY=${{ steps.find-subdirectory.outputs.subdirectory }}
          README_PATH="$GITHUB_WORKSPACE/Projects/$SUBDIRECTORY/README.md"

          echo "Updating README in Subdirectory: $SUBDIRECTORY"
          echo "Wiring Diagram Path: $DIAGRAM_PATH"
          echo "README Path: $README_PATH"

          # Generate the Markdown image tag for the Wiring Diagram
          IMAGE_TAG="![Wiring Diagram](./$DIAGRAM_PATH)"

          # Insert the image tag below the '## Wiring Diagram' line in the README file
          sed -i '/^## Wiring Diagram/ a\'"$IMAGE_TAG" "$README_PATH"

          # Print the updated README file for verification
          cat "$README_PATH"

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Add Wiring Diagram to README [skip ci]"
          git push
