name: Add Wiring Diagram to README

on:
  push:
    branches:
      - test_workflow

jobs:
  add-wiring-diagram:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Find Wiring Diagram file
        id: find-file
        run: |
          commit_file=$(git log --pretty=format: --name-only --diff-filter=AM HEAD -- '*Wiring Diagram.png' | head -n 1)
          if [[ -n "$commit_file" ]]; then
            echo "::set-output name=file::$commit_file"
          else
            echo "No Wiring Diagram file found in the latest commit"
            exit 1
          fi

      - name: Extract subdirectory name
        id: extract-subdirectory
        run: |
          file_path="${{ steps.find-file.outputs.file }}"
          subdirectory=$(dirname "$file_path")
          echo "::set-output name=subdirectory::$subdirectory"

      - name: Check if README.md exists
        id: check-readme
        run: |
          subdirectory="${{ steps.extract-subdirectory.outputs.subdirectory }}"
          readme_file="$subdirectory/README.md"
          if [[ -f "$readme_file" ]]; then
            echo "::set-output name=readme::$readme_file"
          else
            echo "README.md file not found in the subdirectory"
            exit 1
          fi

      - name: Insert Wiring Diagram image
        id: insert-image
        run: |
          readme_file="${{ steps.check-readme.outputs.readme }}"
          if grep -qPzo '## Wiring Diagram\n\n\n## Circuit Schematic' "$readme_file"; then
            commit_file="${{ steps.find-file.outputs.file }}"
            image_line="![Wiring Diagram](./$(basename "$commit_file"))"
            sed -i "/## Wiring Diagram/a$image_line" "$readme_file"
            echo "Image file added to README.md between '## Wiring Diagram' and '## Circuit Schematic'"
          else
            echo "The space between '## Wiring Diagram' and '## Circuit Schematic' is not empty"
          fi
